### ISSUE TITLE
Feature: WebAudio Support

### ISSUE THREAD

**Issue by Technohacker** [walmik/scribbletune#31]
Hello :)
First of all, excellent library :D

Bringing this JS library to the browser stage will be really nice (browser live coding/jamming sessions anyone?). And since the WebAudio API has support for MIDI, it would be a good fit.

I could try implementing this and making a PR but just wanted opinions :)
Cheers!

**Comment by Partysun** [comment]
@Technohacker , Do you plan to make the connection between midi devices and this library or make a real time sound generation?

**Comment by walmik** [comment]
Another way to look at it is to use Scribbletune in conjunction with another lib that already has the web audio api abstracted away nicely.. for eg. Tone.js which is a pretty robust library already https://github.com/Tonejs/Tone.js

I had tried bringing Scribbletune to the browser with browserify and it worked great! Since Typed Arrays can be used in the browser, I think this should be doable.

The additional work would involve making the `midi` method in Scribbletune to export binary data (not fix it to a MIDI file) and feed that to something like Tone.js

**Comment by walmik** [comment]
I hope its fairly obvious, what @Technohacker has (knowingly or unknowingly) suggested via this thread is the not-so-distant future of music production... where everything is in the browser with real time collaborations from scripters and musicians! Some folks are already doing it.. for instance take a look at [Soundation](https://soundation.com/) They dont use neither Scribbletune nor Tone.js but they ve put together something pretty impressive! I m sure folks from Ableton, Properllerhead, Cubase etc have already begun experimenting with this thought albeit in stealth mode coz there s no real news about it... If we can create a free open source alternative before them, we can give them a run for their money! :D

**Comment by Technohacker** [comment]
@walmik @partysun Yes, I meant music production in the browser. Nice to see progress :D

**Comment by walmik** [comment]
Absolutely! I love MIDI.js! 

Scribbletune is just a declarative way to make the music part easier (scales, chords, patterns etc). Abstractions to MIDI & Audio web APIs are certainly the bigger & indispensable part of the rails.

**Comment by walmik** [comment]
I think we ve established that Scribbletune doesnt need to have direct support for Web Audio. An abstraction of the Web Audio API should be used in conjunction. Same applies for hooking up MIDI devices to the browser. Thanks for your ideas & comments @Technohacker @Partysun @hrgui  Closing this issue now :)

**Comment by hrgui** [comment]
for an example of how scribbletunes can be possibly used with Web Audio API, here's an example:
https://github.com/hrgui/midi-test-playground/blob/master/index.js

also since scribbletunes does have a dependency on fs, in order to use it in webpack i had to do something:
https://github.com/hrgui/midi-test-playground/blob/master/webpack.config.js#L10

**Comment by Technohacker** [comment]
@walmik Good to hear :)

**Comment by MaximeMaillet** [comment]
timidity for translate .mid to .ogg + EventSource + nodemon and you can set your files with preview in real time.

https://github.com/MaximeMaillet/musicnodejs

Just for playing :)
