### ISSUE TITLE
Breaking up beats in a pattern

### ISSUE THREAD

**Issue by jscheel** [walmik/scribbletune#35]
I started writing a PR that would allow you to to put spaces in patterns for organization:

```
pattern: 'x_x_  x_x_  x_x_  xxxx'
```
The pattern would simply remove the spaces before processing the clip. However, I'm not entirely sure that is the best approach, as users may want to get the length of the pattern. This would lead to more work for the user to remember to filter out spaces. Instead, I wonder if a simple example of string concatenation in the docs would suffice. Something like this:

```
pattern: 'x_x_' + 'x_x_' + 'x_x_' + 'xxxx'
```

Any thoughts?

**Comment by NBumgardner** [comment]
The [README.md ](https://github.com/walmik/scribbletune#patterns) includes a `.repeat(3)` example for using string operations on patterns.

If you are looking for more ways to break up patterns visually in your codebase, you could try a joined array:

```
const scribble = require("scribbletune");

// Each line is 4 beats of music.
let melody = [
	'c3', 'd3', 'e3', 'd3', 'c3',
	'd3', 'e3', 'd3', 'g2'
];
let pattern = [
	'x___'.repeat(3), 'x_x_',
	'x___'.repeat(3), 'x_--'
].join('');

let clip = scribble.clip({
	notes: melody,
	pattern: pattern
});
scribble.midi(clip, 'song.mid');
```
Another idea is to make a function to print a clip's patterns in a broken-up way, if you just want to see the input pattern with spacing by beat. Maybe by outputting the pattern in a loop with a space added after every 4th character.

The tool works without a whitespace filtering feature, so maybe this issue could be labeled as an *enhancement* or *feature request*?

Personally I enjoy the simplicity, since it errors if I input incorrect characters for a pattern.

**Comment by jscheel** [comment]
Hmm, I was thinking of something more akin to Rust's numeric literals. For example `1_000 === 1000`. it's simply a way to improve readability of the code. Or, in this case, readability of a pattern. If you have a complex pattern of 32 `x`, `_`, and `-`, it may help to break those up into identifiable beats. To avoiding adding anything to the codebase, it may be better to use simple concatenation, as I suggested before.

**Comment by walmik** [comment]
Looks like you guys asked and answered yourself :D Thanks so much!
I agree simple concatenation or joins on arrays is the best way forward 👍
