### ISSUE TITLE
Love this ! can we setup automation to import clips into Ableton.

### ISSUE THREAD

**Issue by DhavalW** [walmik/scribbletune#46]
First off, Loved this whole idea !
The kicker for me is how this could be used to easily create quite complex harmonies & beat patterns. Im going to try to expand on that soon. We could also use it to co-relate music theory to known number patterns / mathematical formulas or vice versa, use math formulas to construct music patterns.

Possibly even have a new kind of UI that allows you to visualize chord / harmony / beat patterns as editable mathematical charts. *mind explodes*

For the moment, I felt it'd be great if we could automate the process of importing the clips into ableton. Seems tedious, especially as the modifications grow. 

we could have predefined channels as bass /  drums / wtev in ableton. The automation simply matches filename to channel name and imports it in. 

Possibly a max for live automaton OR scribble tunes directly exporting an ableton project ?
any  thoughts ?

**Comment by walmik** [comment]
Wow, thank you so much for the kind words.. and here are some really good ideas too!

I ve tried both of the things you ve mentioned and am keen on getting there in terms of making it a reality. 

### Play MIDI directly
So for the first option (where we want to directly play the MIDI in Ableton). First we need to [create a virtual MIDI port](https://help.ableton.com/hc/en-us/articles/209774225-Using-virtual-MIDI-buses-in-Live) so that we can send MIDI messages to it with JavaScript. Then we can npm install a module called midi and try the following with Ableton Live opened up:

```
var midi = require('midi');

// Set up a new output.
var output = new midi.output();

// Count the available output ports.
// output.getPortCount();

// Get the name of a specified output port.
console.log(output.getPortName(0));

// Open the first available output port.
output.openPort(0);

// Send a MIDI message.
output.sendMessage([144,60,127]);

// Close the port when done.
output.closePort();
```

Executing that ^ will produce a MIDI message to the virtual port and it will play out whatever instrument you had on the selected channel.


### Export a Ableton project
There s an abandoned project on Github called ... uh... [ableton](ableton) ... which lets us look into the option of packing a Ableton project directly. So the `.als` file of Ableton, is like a zipped XML like structure. This structure is pretty painful to read through or construct by hand (I bet Ableton programmers have some proprietary method of working with this file).. however it s not entirely unreadable.. you can use some unzip program and unpack a `.als` file and see for yourself what it takes to make a Ableton project together, which hopefully we can use to produce these files from scribbletune.

Anyway, so that s all I ve got. Lemme know what you think :)
