### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [walmik/scribbletune#70]
Hi @walmik, so I would like to know if you have something in your mind for this logo, any ideas?

Scribbletune it´s a project to create music with JavaScript, right? 

Can you tell me o more to get inspired.

Greetings!

**Comment by walmik** [comment]
Thank you @zuurw for offering your creativity for the logo of this project.

This project started a while ago to solve a personal problem. While creating electronic dance music I found myself repeating too many steps again and again for every track. In electronic dance music, as you might know, there are a lot of repeating elements in the track. It's loop based music to a large extent. I wanted to programmatically get done with the common elements which are so pattern based so that I could focus more on the melodies and such. From there it went on to become much more than that.

Initially it was a terminal based Node module where it would export [MIDI](http://www.indiana.edu/~emusic/361/midi.htm) files using an existing project called [jsmidgen](https://github.com/dingram/jsmidgen) using a simple pattern language I created  (it s made of `x`, `-` and `_`) . These MIDI files would then be required to be imported into a music production software like Ableton Live. This functionality still exists and I continue to use it myself even today. But earlier this year I got interested in another project called [Tone.js](https://tonejs.github.io/) and saw that one can play MIDI data right in the browser, thanks to the WebAudioAPI Hence I used Tone.js to provide that functionality via Scribbletune to the browser as well. Now users can create musical ideas using the same pattern language that I had created to create loops in the browser. Then I also added functionality such that developers can create music production software in the browser itself. So in a way Scribbletune (I use it as one word) is a library to enable the creation of music with JavaScript in the terminal and the browser. 

The goal is to come to a point where you dont need any software or hardware or even instruments to create music. Just code away to glory! :D

Here are a coupla links of the talks I gave (it should give you a very good idea what scribbletune is all about). The first one is when scribbletune was just a terminal based module and the second one is when I added browser support:

- [SF Node 2017 at Github's SF office](https://www.youtube.com/watch?v=iwuZzp_ZnLo)
- [JS.LA 2018 at Smarket's LA office](https://www.youtube.com/watch?v=SySdchiCjsQ)

**Comment by zuurw** [comment]
Hey @walmik, I saw your videos and this project it´s really amazing, like it very much!

For this design I will focus on what this project does, which is to create dance music.
Do you have any special requests for the logo?

**Comment by zuurw** [comment]
Hey @walmik, I saw your videos and this project it´s really amazing, like it very much!

For this design I will focus on what this project does, which is to create dance music.
Do you have any special requests for the logo?

**Comment by zuurw** [comment]
Hello @walmik, I start to design something for this project and create this, see if you undestand the concept :)

![proposal](https://user-images.githubusercontent.com/40801473/42605029-a68021d0-856d-11e8-921f-8d77e584199f.png)

**Comment by zuurw** [comment]
Hi @walmik I create this variation of the logo, what do you think?

![proposal2](https://user-images.githubusercontent.com/40801473/42626097-51157df4-85c1-11e8-8132-a54b0aaa6c5b.png)

**Comment by walmik** [comment]
HI @zuurw I am thankful to you for putting so much time and effort on this.

Though I m not so sure if we should add more shape elements to the logo. From your initial design I had liked the vertical lines with the rectangles in them that suggested settings or patterns. It also reminded me of a piano roll of a music software (and that s very close to what Scribbletune ultimately generates). This is how a piano roll looks

![piano-roll](https://user-images.githubusercontent.com/467030/42650405-2bcc91b8-85c1-11e8-9673-7eb29f7a6ced.jpg)

If I had to chose just one from so many wonderful options from you then I d chose the option presented on the bottom left corner of your initial design. I m not completely sure bout the phonograph record, but from a broad perspective, it might just be in the right direction.

Having said all that, I d rather depend on your judgement coz you are clearly an artist :)

**Comment by zuurw** [comment]
I create this version with piano keys

![proposal 3](https://user-images.githubusercontent.com/40801473/42683756-20eefa9a-8686-11e8-944f-037a3f58a18d.png)

**Comment by zuurw** [comment]
after the last version I try to put the logo in a square shape and I like more this version.

And you can make nice variations of the logo.

See if you like it.

![proposal 4](https://user-images.githubusercontent.com/40801473/42684872-4853281a-8689-11e8-9f4d-8c5dd42f832f.png)

**Comment by walmik** [comment]
HI @zuurw, I do like this square shaped variations too. All 4 options are great!

**Comment by zuurw** [comment]
Hi @walmik I create the PR.

**Comment by zuurw** [comment]
Hi @walmik 
Did you see the PR, is there something wrong?

Best Regards!

**Comment by zuurw** [comment]
Hi @walmik 
Do you need more help? do yo have any other projects to work?

Best Regards!

**Comment by walmik** [comment]
Hi @zuurw I ve started putting together a design for scribbletune.com where i intend to use the logo you created. You can take a look at the preliminary stuff I ve put together (I generally dont have much free time hence development is slow - but I ve started publishing whatever is ready - I still havent put a "About" page where I ll put your name in the credits but I ll do that in the coming week)

Lemme know what you think http://scribbletune.com/
